model_list:
  - model_name: gpt-oss
    litellm_params:
      model: openai/gpt-oss
      api_base: http://127.0.0.1:8013/v1
      api_key: none
  - model_name: qwen-coder
    litellm_params:
      model: openai/qwen-coder
      api_base: http://127.0.0.1:8012/v1
      api_key: none
